config/routes.rb
Rails.application.routes.draw do

  authenticated :user, lambda {|u| u.plan == "Student"} do
    root to: "students#index"
  end

  authenticated :user, lambda {|u| u.plan == "Tutor"} do
    root to: "tutors#index"
  end

  unauthenticated :user do
    root to: "home#index"
  end

  devise_for :users, controllers: {
    registrations: 'registrations'
  }

  resources :tutors
  resources :students
  resources :charges

  # resources :users do
  #   resources :tutors
  #   resources :students
  # end


  get 'home/index'
  get 'home/pricing'
  get 'home/about'
  get 'student/parent'
  get 'home/terms_of_service'
  get 'home/stats'
  get 'home/help_service'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user, optional: true

  validates :parent_email, presence: true if @under_age == true
  # validates :description, :grade, presence: true

  Grade = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]
  Gender = ["Male", "Female", "Other"]
end

app/models/tutor.rb
class Tutor < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  acts_as_punchable

  belongs_to :user, optional: true
  # before_create :activate_user

  validates :description, :price, :gender, :subjects, presence: true
  validates_numericality_of :price, :phone_number

  Gender = ["Male", "Female", "Other"]
  Subjects = ["Math", "Science", "Chemistry", "Physics", "Biology", "English", "History", "Computer Science", "Art", "Geography", "Business"]
  Currency = ["$", "£", "€"]

  # def activate_user
  #   [:active] = true
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :tutor, dependent: :destroy
  has_one :student, dependent: :destroy

  validates :name, :email, :password, :password_confirmation, :plan, :age, presence: true


  Plan = ['Tutor ($14.99/month)', "Tutor"], ['Student (Free/month)', "Student"]   # ['Whats shown on screen', "Value saved to database"]

  Age = []
	for i in 1..100
	  Age << i
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    # @amount = 1999

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken],
      :plan => 'plan_DhfpffGzF1lxcG'
    )

    # charge = Stripe::Charge.create(
    #   :customer    => customer.id,
    #   :amount      => @amount,
    #   :description => 'A one month subscription to Tutorhacks.',
    #   :currency    => 'cad'
    # )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def pricing
    @pricing = true
  end

  def about
    @about = true
  end

  def terms_of_service
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def after_sign_in_path_for(resource)
    if resource.plan == 'Tutor'
      new_charge_path(resource.id)
    else
      new_student_path(resource.id)
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :plan, :age)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :age)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /students
  # GET /students.json
  def index
    @student = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = current_user.build_student
    @under_age = false

    if @student.user.age < 18
      @under_age = true
    end
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = current_user.build_student(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to new_students_path, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def parent
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:description, :parent_email, :grade, :gender)
    end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tutors
  # GET /tutors.json
  def index
    @tutor = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
    if current_user.id != @tutor.user_id || current_user.plan == "Student"
      @tutor.punch(request)
    end
  end

  # GET /tutors/new
  def new
    @tutor = current_user.build_tutor
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = current_user.build_tutor(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: "#{@tutor.user.name} was successfully created." }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: "#{@tutor.user.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: "#{@tutor.user.name} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:description, :price, :avatar, :gender, :subjects)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def name
    current_user.name
  end
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$19.99</strong>! for a onemonth subscription</h2>

<%= link_to "Continue", new_tutor_path %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $19.99</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="1999"
          data-locale="auto"></script>
<% end %>

app/views/home/_footer.html.erb
<footer class="footer has-background-white-ter">
  <div class="tile is-ancestor">
    <div class="tile is-parent is-4">
      <div class="tile is-child has-text-centered">
        <ul>
          <li class="subtitle is-bold has-text-black">Media</li>
          <a class="has-text-grey-dark"> <!-- href="https://www.Instagram.com/tutorhack">-->Instagram</a><p />
          <a class="has-text-grey-dark">testing</a>
        </ul>
      </div>
    </div>
    <div class="tile is-parent is-4">
      <div class="tile is-child has-text-centered">
        <ul>
          <li class="subtitle is-bold has-text-black">Resources</li>
          <a class="has-text-grey-dark" href="<%= home_pricing_path %>">Pricing</a><p />
          <a class="has-text-grey-dark" href="<%= home_about_path %>">About</a><p />
          <!-- <a class="has-text-grey-dark" href="<#%= home_stats_path %>">Stats</a><p /> -->
          <a class="has-text-grey-dark" href="<%= home_help_service_path %>">Help Service</a>
        </ul>
      </div>
    </div>

    <div class="tile is-parent is-4">
      <div class="tile is-child has-text-centered">
        <ul>
          <li class="subtitle is-bold has-text-black">Admin</li>
          <a href="<%= new_user_registration_path %>" class="has-text-grey-dark">Sign Up<a><p />
          <a href="<%= new_user_session_path %>" class="has-text-grey-dark">Log in</a>
        </ul>
      </div>
    </div>
  </div>
  <hr class="has-background-black" style="width: 80%; margin-left: 10%; margin-right: 10%;">

  <section>
    <div class="tile is-ancestor has-text-centered">
      <div class="tile is-parent">
        <div class="tile is-child">
          <a class="navbar-icon" href="<%= root_path %>">
            <div style="width: 55px; height: 55px; margin-bottom: -11%; margin-left: 15%;">
              <%= image_tag("Easel-icon.png") %>
            </div>

            <a class="#" href="<%= root_path %>" style="font-size: 155%; font-family: Comic Sans MS; margin-left: -10%;">Tutorhacks</a>
          </a>
        </div>
      </div>

      <div class="tile is-parent">
        <div class="tile is-child" style="padding-top: 2.5%;">
          <b>All rights reserved to Tutorhacks</b>
          <br>Copyright &copy;<%= Date.today.year %></br>
        </div>
      </div>

      <div class="tile is-parent">
        <div class="tile is-child" style="padding-top: 2.5%;">
          <b>Made by students for students with &lt;/&gt; and &hearts; from Ottawa<b>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/home/_navbar.html.erb
<nav class="navbar is-fixed-top is-transparent">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-icon" href="<%= root_path %>" style="width: 55px; margin-top: 2.5%; margin-bottom: -5%;">
        <%= image_tag("Easel-icon.png") %>

        <a class="#" href="<%= root_path %>" style="margin-top: 6.5%; font-size: 155%; font-family: Comic Sans MS; margin-left: 3%">Tutorhacks</a>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarMenuHeroA" class="navbar-menu">
      <div class="navbar-end">
        <a class="navbar-item <% if @pricing == true %> is-active <% end %>" href="<%= home_pricing_path %>">
          Pricing
        </a>
        <a class="navbar-item <% if @about == true %> is-active <% end %>" href="<%= home_about_path %>" style="margin-right: 10%;">
          About Us
        </a>

        <!-- <a class="navbar-item <% if @stats == true %> is-active <% end %>" href="<%= home_stats_path %>" style="margin-right: 10%;">
          Stats
        </a> -->

        <span class="navbar-item">
          <a class="button is-danger is-rounded is-outlined mr3" href="<%= new_user_session_path %>" style="font-size: 115%;">Login</a>
        </span>

      </div>
    </div>
  </div>
</nav>

app/views/home/help_service.html.erb
<h1 class="title">Help service page</h1>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- <link rel="stylesheet" href="/stylesheets/debug.css"> -->
	</head>
	<body>

		<%= render "navbar" %>

		<section class="hero is-dark is-fullheight is-bold">
		  <div class="hero-body" style="margin-bottom: -15%;">
		    <div class="container">
					<div class="title is-capitalized" style="font-size: 400%;">Let us help you</div>
					<div class="subtitle mt2" style="width: 45%;">Sometimes completing your homework can be difficult, find someone who can help. Sign up for free today.</div>
					<a class="button is-link is-rounded is-capitalized" href="<%= new_user_registration_path %>" style="min-width: 20%; font-size: 145%;">Sign up</a>
		    </div>
		  </div>

			<div class="student-speech-bubble">
				<%= image_tag("home/speech-bubble.png") %>
			</div>
			<div class="student-a">
				<%= image_tag("home/A-plus.png") %>
			</div>

			<div class="home-image" style="height: 45%; width: 35%;">
				<%= image_tag("home/homescreen-students.png") %>
			</div>

			<div class="arrow bounce has-text-centered mb3">
			  <a class="fa fa-arrow-down fa-2x" href="#"></a>
			</div>
		</section>

		<section class="hero-body mb4">
			<div class="title has-text-centered has-text-black" style="margin-bottom: 5%; font-family: arial black;">
				<b>Why Tutorhacks?</b>
			</div>

			<div class="tile is-ancestor is-vertical">
				<div class="tile is-parent notifaction has-text-white">
					<div class="tile is-child notifaction has-background-info notification is-7" style="height: 325px;">
						<p class="title pt2">Quick</p>
          	<p class="subtitle pt3" style="line-height: 30px; text-indent: 40px;">The speed of making an account is very important to us. Make a fully customizable profile in under 5 minutes. Once done, you are free to explor the tutors in your neighborhood with complete freedom.</p>

						<%= image_tag("home/fast-clock-icon.png", alt: "Quick", class: "mr5", style: "width: 150px; height: 125px; float: right;") %>
					</div>

					<div class="tile is-child"></div>
				</div>

				<div class="tile is-parent notifaction has-text-white">
					<div class="tile is-child"></div>

					<div class="tile is-child notifaction has-background-info notification is-7" style="height: 325px;">
						<p class="title pt2">Effective</p>
          	<p class="subtitle pt3" style="line-height: 30px; text-indent: 40px;">It really is effective and easy to use. Our simple user interface makes it easy to navigate and help is on every corner. If you still can't figure it out, visite the help center and maybe your question can be answered.</p>

						<%= image_tag("home/deploma-icon.png", alt: "Effective", class: "mr5", style: "width: 125px; height: 125px; float: right;") %>
					</div>
				</div>

				<div class="tile is-parent notifaction has-text-white">
					<div class="tile is-child notifaction has-background-info notification is-7" style="height: 325px;">
						<p class="title pt2">Safe</p>
          	<p class="subtitle pt3" style="line-height: 30px; text-indent: 40px;">Safety is our number one priority. Our safety measures include if you are a student and you are under the age of 18 you have to supply a secondary email, who are notified of everything you are doing.</p>

						<%= image_tag("home/key-icon.png", alt: "Safe", class: "mr5", style: "width: 125px; height: 125px; float: right;") %>
					</div>

					<div class="tile is-child"></div>
				</div>
			</div>
		</section>


		<section class="mb3 about-tutor-count container" style="height: 550px;">
			<div class="has-text-centered">
				<div class="title is-size-2 pt4">Steps</div>

				



			</div>
		</section>


		<section class="hero is-medium is-bold" style="background-color: #343477;">
		  <div class="hero-body">
		    <div class="container">
		      <h1 class="title has-text-white ml5">
						Are you ready to get started?

						<div class="" style="float: right;">
							<a class="button is-large is-white is-capitalized" href="<%= new_user_registration_path %>">Create an account</a>
							<a class="button is-large is-white is-outlined is-capitalized" href="<%= home_about_path %>">More about us</a>
						</div>
		      </h1>
		    </div>
		  </div>
		</section>



		<%= render "footer" %>

	</body>
</html>

app/views/home/pricing.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<!-- <link rel="stylesheet" href="/stylesheets/debug.css"> -->
	</head>
	<body>
		<%= render "navbar" %>

		<section class="hero is-primary is-fullheight">
			<div class="has-text-centered mt6">
				<div class="title is-1 is-underlined">Plans + Pricing</div>
			</div>

		  <div class="hero-body" style=" width: 90%; margin-left: 5%; margin-right: 5%;">
		    <div class="tile is-ancestor">
		    	<div class="tile is-6">
		    		<div class="tile is-parent">
		    			<article class="tile is-child is-white notification has-text-centered">

								<%= image_tag("pricing/pricing-student-icon.png", :style => "width: 128px; height: 128px; margin-top: -6%; margin-bottom: 4%;") %>

								<div class="subtitle has-text-centered has-text-black" style="margin-bottom: -4%; font-size: 170%;">Student Plan</div>
								<hr class="hr">

								<div class="content">
									<div class="has-text-info">
										<b style="font-size: 165%;">Free</b>/<sub style="font-size: 95%;">Month</sub>
									</div> <p/>
									<p><b>Unlimited</b> searches</p>
									<p><b>Unlimited</b> requests</p>
									<p><b>Fully</b> custom</p>
									<p><b>Full Access</b> to website</p>
									<p></p>
									<a class="button is-link is-rounded" href="<%= new_user_registration_path %>" style="min-width: 20%; font-size: 115%;">Sign up</a>
								</div>
		    			</article>
		    		</div>
		    	</div>

					<div class="tile is-6">
		    		<div class="tile is-parent">
		    			<article class="tile is-child is-white notification has-text-centered">

								<%= image_tag("pricing/pricing-tutor-icon.png", :style => "width: 128px; height: 128px; margin-top: -6%; margin-bottom: 4%;") %>

								<div class="subtitle has-text-centered has-text-black" style="margin-bottom: -4%; font-size: 170%;">Tutor Plan</div>
								<hr class="hr">

								<div class="content">
									<div class="has-text-info">
										<b style="font-size: 165%;">$9.99</b>/<sub style="font-size: 95%;">Month</sub>
									</div> <p/>
									<p><b>All Students</b> can search your profile</p>
									<p><b>Unlimited</b> subjects</p>
									<p><b>Fully</b> custom</p>
									<p><b>Full Access</b> to website</p>
									<p></p>
									<a class="button is-link is-rounded" href="<%= new_user_registration_path %>" style="min-width: 20%; font-size: 115%;">Sign up</a>
								</div>
		    			</article>
		    		</div>
		    	</div>
		    </div>
		  </div>
		</section>

		<section class="hero-body">
			<div class="title has-text-centered has-text-black">
				<b><i>FAQ</i></b>
			</div>

			<div class="tile is-ancestor has-background-white-bis pb4" style="margin-left: 5%; margin-right: 5%; margin-bottom: 4%; border-radius: 3%; margin-top: 2%;">
				<div class="tile">
					<div class="tile is-parent">

						<div class="tile is-child is-size-4" style="padding-right: 5%;">
							<div>
								<div class="has-text-danger mt5"><b>Q: What comes with the student plan?</b></div>
								<div class="has-text-link">A: With the student plan you get unlimited searches on tutors in your area, unlimited tutor requests, [MORE] and profile customization 24/7.</div>
							</div>

							<div>
								<div class="has-text-danger mt5"><b>Q: What comes with the student plan1?</b></div>
								<div class="has-text-link">A: This is just a test sentencd and will be replaced with something that is better. This is just made to make the sentence longer.</div>
							</div>

							<div>
								<div class="has-text-danger mt5"><b>Q: What comes with the student plan1?</b></div>
								<div class="has-text-link">A: This is just a test sentencd and will be replaced with something that is better. This is just made to make the sentence longer.</div>
							</div>
						</div>

						<div class="tile is-child is-size-4 is-vertical">
							<div>
								<div class="has-text-danger mt5"><b>Q: What comes with the tutor plan?</b></div>
								<div class="has-text-link">A: With the tutor plan you get access to select as many subjects as you want, and profile customization 24/7.</div>
							</div>

							<div>
								<div class="has-text-danger mt5"><b>Q: Can you pay with Paypal?</b></div>
								<div class="has-text-link">A: Currently you are only allowed to pay with debit or credit card and not with Paypal. But adding paypal to the payment choices is on the top of out list.</div>
							</div>

							<div>
								<div class="has-text-danger mt5"><b>Q: What comes with the student plan2?</b></div>
								<div class="has-text-link">A: This is just a test sentencd and will be replaced with something that is better. This is just made to make the sentence longer.</div>
							</div>
						</div>

					</div>
				</div>
			</div>
		</section>


		<section class="hero is-medium is-bold" style="background-color: #343477;">
		  <div class="hero-body">
		    <div class="container">
		      <h1 class="title has-text-white">
						Are you ready to get started?

						<div class="" style="float: right;">
							<a class="button is-large is-white is-capitalized" href="<%=new_user_registration_path %>">Create an account</a>
							<a class="button is-large is-white is-outlined is-capitalized" href="<%= home_about_path %>">More about us</a>
						</div>
		      </h1>
		    </div>
		  </div>
		</section>




    <%= render "footer" %>
	</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_navbar.html.erb
<nav class="navbar is-fixed-top is-transparent" style="background-color: #E0E0E0; margin-bottom: 10%; height: 65px;">
  <div class="container">

    <div class="navbar-menu" style="">
      <a href="<%= root_path %>" class="navbar-start is-size-3 has-text-black">
        <%= image_tag("Easel-icon.png", style: "height: 45px; width: 45px; margin-top: 5%;") %>
        <div style="margin-top: 3%; margin-left: 5%;">Tutorhacks</div>
      </a>

      <div class="navbar-end is-size-5 has-text-black dropdown">
        <div class="dropdown is-hoverable">
          <div class="dropdown-trigger">
            <div class="" aria-haspopup="true" aria-controls="dropdown-menu4" style="margin-top: 8%;">
              <span><%= current_user.email %></span>
              <span class="icon is-medium">
                <i class="fas fa-angle-down" aria-hidden="true"></i>
              </span>
            </div>
          </div>
          <div class="dropdown-menu" id="dropdown-menu4" role="menu">
            <div class="dropdown-content">
              <div class="dropdown-item is-size-6">
                <%# if @singed_in %>
                  <%#= link_to "Show profile", student_path, style: "margin-top: 5%;", class: "has-text-black" %><p />
                  <%#= link_to "Edit profile", edit_student_path(@student), style: "margin-top: 5%;", class: "has-text-black" %><p />
                <%# end %>

                <%= link_to "Account detail", edit_user_registration_path(@user), style: "margin-top: 5%;", class: "has-text-black" %><p />
                <%= link_to "Logout", destroy_user_session_path, method: :delete, style: "margin-top: 5%;", class: "has-text-black" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/new.html.erb
<%= render 'navbar' %>

<div class="pv4">
  <%= render 'form', student: @student %>
</div>

app/views/students/parent.html.erb
parent page

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Description:</strong>
  <%= @student.description %>
</p>


<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/tutors/_navbar.html.erb
<nav class="navbar is-transparent">
  <div class="container">
    <div class="navbar-brand">
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div id="navbarMenuHeroA" class="navbar-menu">
      <div class="navbar-end">
        <a class="navbar-item is-active" href="<%#= home_pricing_path %>">
          <%= current_user.email %>
        </a>

        <span class="navbar-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "button is-danger is-rounded is-outlined mr3" %>
        </span>

      </div>
    </div>
  </div>
</nav>


<aside class="menu tutor-menu" style="">
  <p class="menu-label">
    General
  </p>
  <ul class="menu-list">
    <li><a>Dashboard</a></li>
    <li><a>Customers</a></li>
  </ul>
  <p class="menu-label">
    Profile
  </p>
  <ul class="menu-list">
    <li><a>View profile</a></li>
    <li><a>Edit</a></li>
    <li><a>Add a member</a></li>
  </ul>

  <p class="menu-label">
    Administration
  </p>
  <ul class="menu-list">
    <li>
      <a class="is-active">Manage Your Students</a>
      <ul>
        <li><a>Email</a></li>
        <li><a>Calender</a></li>
        <li><a>Add a member</a></li>
      </ul>
    </li>
  </ul>
</aside>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form', tutor: @tutor %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<%= render "navbar" %>

<h1>Tutors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutor.each do |tutor| %>
      <% if current_user.id == tutor.user_id %>
        <td><%= tutor.user.name %></td>
        <td><%= tutor.description %></td>
        <td><%= tutor.price %></td>
        <td><%= tutor.gender %></td>
        <td><%= link_to 'Show', tutor %></td>
        <td><%= link_to 'Edit', edit_tutor_path(tutor) %></td>
        <td><%= link_to 'Destroy', tutor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    <% end %>
    </tr>
  </tbody>
</table>

<br>

app/views/tutors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tutor.user.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tutor.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tutor.price %>
</p>


<% time = Time.parse(@tutor.created_at.to_s) %>
<p class="has-text-gray has-text-centered mb2 f6">Created: <%= time_ago_in_words(time) %> ago </p>
<p class="has-text-gray has-text-centered fg mb1 f7">Viewed: <%= @tutor.hits %> <%= @tutor.hits == 1 ? "time" : "times" %></p>

<%= link_to 'Edit', edit_tutor_path(@tutor) %> |
<%= link_to 'Back', tutors_path %>